#My blackjack training app!

import random
import os

DB_HOST = "localhost"
DB_USER = os.getenv("DB_USER")
DB_PASS = os.getenv("DB_PASS")
DB_NAME = "blackjack"
CHART_NAME = "Hit/Stand"

ranks = ["A","2","3","4","5","6","7","8","9","10","J","Q","K"]
suits = ["♠","♥","♦","♣"]

def make_deck():
    deck = []

    for _ in range (6):
        for suit in suits:
            for rank in ranks:
                deck.append(rank + suit)
    
    

    random.shuffle(deck)
    return deck

def card_rank(card):
    return card[:-1] # the last char is the suit

def hand_value(hand):
    total = 0
    aces = 0

    for card in hand:
        rank = card_rank(card)
        if rank in ["J","Q","K"]:
            total += 10
        elif rank == "A":
            total += 11
            aces += 1
        else:
            total += int(rank)

    while total > 21 and aces > 0:
        total -= 10
        aces -= 1

    return total

def is_soft(hand):
    total = 0
    aces = 0

    for card in hand:
        rank = card_rank(card)
        if rank == "A":
            total += 11
            aces += 1
        elif rank in ["J","Q","K"]:
            total += 10
        else:
            total += int(rank)

    while total > 21 and aces > 0:
        total -= 10
        aces -= 1

    # compare the total value and the value if all aces as 1
    # to see wether the hand is soft
    all_aces_as_1 = 0
    for card in hand:
        rank = card_rank(card)
        if rank == "A":
            all_aces_as_1 += 1
        elif rank in ["J","Q","K"]:
            all_aces_as_1 += 10
        else:
            all_aces_as_1 += int(rank)


    has_ace = False
    for card in hand:
        if card_rank(card) == "A":
            has_ace = True
            
    return has_ace and (total == all_aces_as_1 + 10)


def show_hand(name, hand, hide_second_card=False):
    if hide_second_card:
        print(name + ": " + hand[0] + " ??")
    else:
        print(name + ": " + " ".join(hand) + "  (total: " + str(hand_value(hand)) + ")")


#for mysql table, j,q,k are viewed as 10
def dealer_upcard_str(card):
    rank = card_rank(card)
    if rank == "A":
        return "A"
    if rank in ["J","Q","K"]:
        return "10"
    return rank



def db_connect():
    import mysql.connector
    return mysql.connector.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASS,
        database=DB_NAME
    )

def get_or_create_chart(cur):
    cur.execute("SELECT chart_id FROM bj_chart WHERE name=%s", (CHART_NAME,))
    row = cur.fetchone()
    if row:
        return row[0]

    cur.execute(
        "INSERT INTO bj_chart (name, notes) VALUES (%s, %s)",
        (CHART_NAME, "Generated by blackjack.py (hit/stand only)")
    )
    return cur.lastrowid

def chart_has_rows(cur, chart_id):
    cur.execute("SELECT COUNT(*) FROM bj_hit_stand WHERE chart_id=%s", (chart_id,))
    return cur.fetchone()[0] > 0

def seed_hit_stand_chart(cur, chart_id):
    """
    This seeds a standard-ish hit/stand chart
    HARD:
      17+ stand
      13-16 stand vs 2-6 else hit
      12 stand vs 4-6 else hit
      11 or less hit
    SOFT:
      19+ stand
      18 stand vs 2,7,8 else hit
      17 or less hit
    """
    dealer_cards = ["2","3","4","5","6","7","8","9","10","A"]

    rows = []

    # HARD totals 4..21
    for total in range(4, 22):
        for up in dealer_cards:
            action = "H"
            if total >= 17:
                action = "S"
            elif 13 <= total <= 16:
                action = "S" if up in ["2","3","4","5","6"] else "H"
            elif total == 12:
                action = "S" if up in ["4","5","6"] else "H"
            else:
                action = "H"
            rows.append((chart_id, "HARD", total, up, action))

    for total in range(13, 22):
        for up in dealer_cards:
            action = "H"
            if total >= 19:
                action = "S"
            elif total == 18:
                action = "S" if up in ["2","7","8"] else "H"
            else:
                action = "H"
            rows.append((chart_id, "SOFT", total, up, action))

    cur.executemany(
        "INSERT INTO bj_hit_stand (chart_id, hand_kind, player_total, dealer_upcard, action) "
        "VALUES (%s,%s,%s,%s,%s)",
        rows
    )

def start_session(cur, chart_id):
    cur.execute("INSERT INTO bj_session (chart_id) VALUES (%s)", (chart_id,))
    return cur.lastrowid

def end_session(cur, session_id):
    cur.execute("UPDATE bj_session SET ended_at=NOW() WHERE session_id=%s", (session_id,))

def get_correct_action(cur, chart_id, hand_kind, player_total, dealer_upcard):
    cur.execute(
        "SELECT action FROM bj_hit_stand "
        "WHERE chart_id=%s AND hand_kind=%s AND player_total=%s AND dealer_upcard=%s",
        (chart_id, hand_kind, player_total, dealer_upcard)
    )
    row = cur.fetchone()
    if row:
        return row[0]
    return "H"

def log_decision(cur, session_id, hand_kind, player_total, dealer_upcard, player_action, correct_action):
    is_correct = 1 if player_action == correct_action else 0
    cur.execute(
        "INSERT INTO bj_decision_log "
        "(session_id, hand_kind, player_total, dealer_upcard, player_action, correct_action, is_correct) "
        "VALUES (%s,%s,%s,%s,%s,%s,%s)",
        (session_id, hand_kind, player_total, dealer_upcard, player_action, correct_action, is_correct)
    )

def get_accuracy(cur, session_id):
    cur.execute(
        "SELECT COUNT(*), SUM(is_correct) FROM bj_decision_log WHERE session_id=%s",
        (session_id,)
    )
    total, correct = cur.fetchone()
    correct = correct or 0
    return total, correct

def get_all_time_accuracy(cur, chart_id=None):
    if chart_id is None:
        cur.execute("SELECT COUNT(*), SUM(is_correct) FROM bj_decision_log")
    else:
        cur.execute("""
            SELECT COUNT(*), SUM(l.is_correct)
            FROM bj_decision_log l
            JOIN bj_session s ON s.session_id = l.session_id
            WHERE s.chart_id = %s
        """, (chart_id,))
    total, correct = cur.fetchone()
    correct = correct or 0
    return total, correct




def main():
    print("Evan's Blackjack Trainer")

    # connect DB
    try:
        conn = db_connect()
        cur = conn.cursor()
        chart_id = get_or_create_chart(cur)

        if not chart_has_rows(cur, chart_id):
            seed_hit_stand_chart(cur, chart_id)
            conn.commit()

        session_id = start_session(cur, chart_id)
        conn.commit()
        db_ok = True
    except Exception as e:
        print("DB not connected. Running without MySQL accuracy tracking.")
        print("Error:", e)
        db_ok = False
        conn = None
        cur = None
        chart_id = None
        session_id = None


    #start game
    deck = make_deck()

    while True:
        if len(deck) < 67:
            deck = make_deck()

        player_hand = []
        dealer_hand = []
        player_hand.append(deck.pop())
        dealer_hand.append(deck.pop())
        player_hand.append(deck.pop())
        dealer_hand.append(deck.pop())

        print("------------------------\n")
        show_hand("Dealer", dealer_hand, hide_second_card = True)
        show_hand("Player", player_hand)

        #check if either player or dealer has blackjack
        player_bj = (hand_value(player_hand) == 21 and len(player_hand) == 2)
        dealer_bj = (hand_value(dealer_hand) == 21 and len(dealer_hand) == 2)

        if player_bj or dealer_bj:
            print("\nDealer :")
            show_hand("Dealer", dealer_hand, hide_second_card = False)

            if player_bj and dealer_bj:
                print("Push")
            elif player_bj:
                print("You win with a Blackjack! :)")
            else:
                print("You lose, dealer has a Blackjack :(")
        else:
            #player decisions
            while True:
                if hand_value(player_hand) > 21:
                    print("\nYou lose, you busted :(")
                    break

                # determine if the hand is soft before the player makes a decision
                # for the database
                
                if is_soft(player_hand):
                    kind = "SOFT" 
                else:
                    kind = "HARD"

                total = hand_value(player_hand)
                up_card = dealer_upcard_str(dealer_hand[0])


                move = input("Hit or Stand? (h/s): ").lower().strip()
                if move == "h":
                    player_action = "H"
                elif move == "s":
                    player_action = "S"
                else:
                    print("Type h or s.")
                    continue

                # compare to chart + log to DB
                if db_ok:
                    correct = get_correct_action(cur, chart_id, kind, total, up_card)
                    log_decision(cur, session_id, kind, total, up_card, player_action, correct)
                    conn.commit()

                # actually do the action
                if player_action == "H":
                    player_hand.append(deck.pop())
                    print()
                    show_hand("Dealer", dealer_hand, hide_second_card=True)
                    show_hand("Player", player_hand)
                else:
                    break

            # dealer plays if player didn't bust
            if hand_value(player_hand) <= 21:
                print("\nDealer shows:")
                show_hand("Dealer", dealer_hand, hide_second_card=False)

                while hand_value(dealer_hand) < 17:
                    print("Dealer hits: ")
                    dealer_hand.append(deck.pop())
                    show_hand("Dealer", dealer_hand, hide_second_card=False)

                p = hand_value(player_hand)
                d = hand_value(dealer_hand)

                if d > 21:
                    print("You win, dealer busted :)")
                elif p > d:
                    print("You win :)")
                elif p < d:
                    print("You lose :(")
                else:
                    print("Push")


        again = input("Play another round? (enter = y/n): ").lower().strip()
        if again == "no" or again == "n":
            break


    # end session + final accuracy
    if db_ok:
        s_total, s_correct = get_accuracy(cur, session_id)
        s_acc = 0 if s_total == 0 else round((s_correct / s_total) * 100, 1)

        a_total, a_correct = get_all_time_accuracy(cur, chart_id)  # or None for global
        a_acc = 0 if a_total == 0 else round((a_correct / a_total) * 100, 1)

        print("\nSession accuracy:", f"{s_correct}/{s_total}", f"= {s_acc}%")
        print("All-time accuracy:", f"{a_correct}/{a_total}", f"= {a_acc}%")

    print("Thanks for playing :)")

if __name__ == "__main__":
    main()