# blackjack.py
# terminal blackjack (grade 12 style)
# uses MySQL hit/stand chart + tracks accuracy

import random

# ---------- CHANGE THESE ----------
DB_HOST = "localhost"
DB_USER = "root"
DB_PASS = "Huk87$Km7@!89"
DB_NAME = "blackjack"
CHART_NAME = "Hit/Stand Basic (no doubles)"
# ---------------------------------

ranks = ["A","2","3","4","5","6","7","8","9","10","J","Q","K"]
suits = ["♠","♥","♦","♣"]

def make_deck():
    deck = []
    for s in suits:
        for r in ranks:
            deck.append(r + s)
    random.shuffle(deck)
    return deck

def card_rank(card):
    return card[:-1]  # last char is suit

def hand_value(hand):
    total = 0
    aces = 0
    for card in hand:
        r = card_rank(card)
        if r in ["J","Q","K"]:
            total += 10
        elif r == "A":
            total += 11
            aces += 1
        else:
            total += int(r)

    while total > 21 and aces > 0:
        total -= 10
        aces -= 1

    return total

def is_soft(hand):
    # soft = has an Ace counted as 11 in the final value
    total = 0
    aces = 0
    for card in hand:
        r = card_rank(card)
        if r == "A":
            total += 11
            aces += 1
        elif r in ["J","Q","K"]:
            total += 10
        else:
            total += int(r)

    # if we had to downgrade an ace, then it becomes less "soft"
    while total > 21 and aces > 0:
        total -= 10
        aces -= 1

    # if there is at least one Ace AND we didn't downgrade all of them, it’s soft
    # easiest way: compare with "all aces as 1"
    all_aces_as_1 = 0
    for card in hand:
        r = card_rank(card)
        if r == "A":
            all_aces_as_1 += 1
        elif r in ["J","Q","K"]:
            all_aces_as_1 += 10
        else:
            all_aces_as_1 += int(r)

    return ("A" in [card_rank(c) for c in hand]) and (total == all_aces_as_1 + 10)

def show_hand(name, hand, hide_first=False):
    if hide_first:
        print(name + ": " + hand[0] + " ??")
    else:
        print(name + ": " + " ".join(hand) + "  (total: " + str(hand_value(hand)) + ")")

def dealer_upcard_str(card):
    r = card_rank(card)
    if r == "A":
        return "A"
    if r in ["J","Q","K"]:
        return "10"
    return r  # "2".."10"

# -------------------- DB STUFF --------------------

def db_connect():
    import mysql.connector
    return mysql.connector.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASS,
        database=DB_NAME
    )

def get_or_create_chart(cur):
    cur.execute("SELECT chart_id FROM bj_chart WHERE name=%s", (CHART_NAME,))
    row = cur.fetchone()
    if row:
        return row[0]

    cur.execute(
        "INSERT INTO bj_chart (name, notes) VALUES (%s, %s)",
        (CHART_NAME, "Generated by blackjack.py (hit/stand only)")
    )
    return cur.lastrowid

def chart_has_rows(cur, chart_id):
    cur.execute("SELECT COUNT(*) FROM bj_hit_stand WHERE chart_id=%s", (chart_id,))
    return cur.fetchone()[0] > 0

def seed_hit_stand_chart(cur, chart_id):
    """
    This seeds a standard-ish hit/stand chart (no doubles).
    HARD:
      17+ stand
      13-16 stand vs 2-6 else hit
      12 stand vs 4-6 else hit
      11 or less hit
    SOFT:
      19+ stand
      18 stand vs 2,7,8 else hit
      17 or less hit
    """
    dealer_cards = ["2","3","4","5","6","7","8","9","10","A"]

    rows = []

    # HARD totals 4..21
    for total in range(4, 22):
        for up in dealer_cards:
            action = "H"
            if total >= 17:
                action = "S"
            elif 13 <= total <= 16:
                action = "S" if up in ["2","3","4","5","6"] else "H"
            elif total == 12:
                action = "S" if up in ["4","5","6"] else "H"
            else:
                action = "H"
            rows.append((chart_id, "HARD", total, up, action))

    # SOFT totals 13..21  (A,2=13 ... A,10=21)
    for total in range(13, 22):
        for up in dealer_cards:
            action = "H"
            if total >= 19:
                action = "S"
            elif total == 18:
                action = "S" if up in ["2","7","8"] else "H"
            else:
                action = "H"
            rows.append((chart_id, "SOFT", total, up, action))

    cur.executemany(
        "INSERT INTO bj_hit_stand (chart_id, hand_kind, player_total, dealer_upcard, action) "
        "VALUES (%s,%s,%s,%s,%s)",
        rows
    )

def start_session(cur, chart_id):
    cur.execute("INSERT INTO bj_session (chart_id) VALUES (%s)", (chart_id,))
    return cur.lastrowid

def end_session(cur, session_id):
    cur.execute("UPDATE bj_session SET ended_at=NOW() WHERE session_id=%s", (session_id,))

def get_correct_action(cur, chart_id, hand_kind, player_total, dealer_upcard):
    cur.execute(
        "SELECT action FROM bj_hit_stand "
        "WHERE chart_id=%s AND hand_kind=%s AND player_total=%s AND dealer_upcard=%s",
        (chart_id, hand_kind, player_total, dealer_upcard)
    )
    row = cur.fetchone()
    if row:
        return row[0]
    # fallback if something missing
    return "H"

def log_decision(cur, session_id, hand_kind, player_total, dealer_upcard, player_action, correct_action):
    is_correct = 1 if player_action == correct_action else 0
    cur.execute(
        "INSERT INTO bj_decision_log "
        "(session_id, hand_kind, player_total, dealer_upcard, player_action, correct_action, is_correct) "
        "VALUES (%s,%s,%s,%s,%s,%s,%s)",
        (session_id, hand_kind, player_total, dealer_upcard, player_action, correct_action, is_correct)
    )

def get_accuracy(cur, session_id):
    cur.execute(
        "SELECT COUNT(*), SUM(is_correct) FROM bj_decision_log WHERE session_id=%s",
        (session_id,)
    )
    total, correct = cur.fetchone()
    correct = correct or 0
    return total, correct

# -------------------- GAME --------------------

def main():
    print("=== Terminal Blackjack ===")
    print("No betting. Play forever until you quit.\n")

    # connect DB
    try:
        conn = db_connect()
        cur = conn.cursor()
        chart_id = get_or_create_chart(cur)

        if not chart_has_rows(cur, chart_id):
            seed_hit_stand_chart(cur, chart_id)
            conn.commit()

        session_id = start_session(cur, chart_id)
        conn.commit()
        db_ok = True
    except Exception as e:
        print("DB not connected. Running without MySQL accuracy tracking.")
        print("Error:", e)
        db_ok = False
        conn = None
        cur = None
        chart_id = None
        session_id = None

    deck = make_deck()

    while True:
        if len(deck) < 15:
            deck = make_deck()

        player = []
        dealer = []
        player.append(deck.pop())
        dealer.append(deck.pop())
        player.append(deck.pop())
        dealer.append(deck.pop())

        print("\n----------------------------")
        show_hand("Dealer", dealer, hide_first=True)
        show_hand("Player", player)

        # check blackjack
        player_bj = (hand_value(player) == 21 and len(player) == 2)
        dealer_bj = (hand_value(dealer) == 21 and len(dealer) == 2)

        if player_bj or dealer_bj:
            print("\nDealer reveals:")
            show_hand("Dealer", dealer, hide_first=False)

            if player_bj and dealer_bj:
                print("Push. (Both blackjack)")
            elif player_bj:
                print("Blackjack! You win.")
            else:
                print("Dealer has blackjack. You lose.")
        else:
            # player turn
            while True:
                if hand_value(player) > 21:
                    print("\nYou busted!")
                    break

                # figure out the state BEFORE the player's decision
                kind = "SOFT" if is_soft(player) else "HARD"
                total = hand_value(player)
                up = dealer_upcard_str(dealer[0])

                move = input("Hit or Stand? (h/s): ").lower().strip()
                if move == "h":
                    player_action = "H"
                elif move == "s":
                    player_action = "S"
                else:
                    print("Type h or s.")
                    continue

                # compare to chart + log to DB
                if db_ok:
                    correct = get_correct_action(cur, chart_id, kind, total, up)
                    log_decision(cur, session_id, kind, total, up, player_action, correct)
                    conn.commit()

                # actually do the action
                if player_action == "H":
                    player.append(deck.pop())
                    print()
                    show_hand("Dealer", dealer, hide_first=True)
                    show_hand("Player", player)
                else:
                    break

            # dealer plays if player didn't bust
            if hand_value(player) <= 21:
                print("\nDealer reveals:")
                show_hand("Dealer", dealer, hide_first=False)

                while hand_value(dealer) < 17:
                    print("Dealer hits...")
                    dealer.append(deck.pop())
                    show_hand("Dealer", dealer, hide_first=False)

                p = hand_value(player)
                d = hand_value(dealer)

                if d > 21:
                    print("Dealer busted! You win.")
                elif p > d:
                    print("You win.")
                elif p < d:
                    print("You lose.")
                else:
                    print("Push. (tie)")

        # show accuracy so far
        if db_ok:
            total, correct = get_accuracy(cur, session_id)
            acc = 0 if total == 0 else round((correct / total) * 100, 1)
            print("\nAccuracy so far:", f"{correct}/{total}", f"= {acc}%")

        again = input("Next round? (enter = yes, q = quit): ").lower().strip()
        if again == "q":
            break

    # end session + final accuracy
    if db_ok:
        end_session(cur, session_id)
        conn.commit()
        total, correct = get_accuracy(cur, session_id)
        acc = 0 if total == 0 else round((correct / total) * 100, 1)
        print("\nFINAL accuracy:", f"{correct}/{total}", f"= {acc}%")
        cur.close()
        conn.close()

    print("\nThanks for playing!")

if __name__ == "__main__":
    main()